/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BatchActions: typeof import('./../components/BatchActions/index.vue')['default']
    ContentPreview: typeof import('./../components/ContentPreview/index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    HtEmpty: typeof import('./../components/HtEmpty/index.vue')['default']
    HtTable: typeof import('./../components/HtTable/index.vue')['default']
    Permission: typeof import('./../components/Permission/index.vue')['default']
    ReviewDialog: typeof import('./../components/ReviewDialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Uploader: typeof import('./../components/Uploader/index.vue')['default']
  }
}
