/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BatchActions: typeof import('./../components/BatchActions/index.vue')['default']
    BatchPublishDialog: typeof import('./../components/BatchPublishDialog/index.vue')['default']
    ContentPreview: typeof import('./../components/ContentPreview/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    HtEmpty: typeof import('./../components/HtEmpty/index.vue')['default']
    HtTable: typeof import('./../components/HtTable/index.vue')['default']
    LazyImage: typeof import('./../components/LazyImage/index.vue')['default']
    NotePublishDialog: typeof import('./../components/NotePublishDialog/index.vue')['default']
    Permission: typeof import('./../components/Permission/index.vue')['default']
    ReviewDialog: typeof import('./../components/ReviewDialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Uploader: typeof import('./../components/Uploader/index.vue')['default']
  }
}
