SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `warehouse_inbound_records`;
CREATE TABLE `warehouse_inbound_records` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `inbound_no` VARCHAR(32) NOT NULL COMMENT '入库单号',
  `goods_id` BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  `goods_code` VARCHAR(100) NOT NULL COMMENT '商品编码',
  `goods_name` VARCHAR(255) NOT NULL COMMENT '商品名称',
  `goods_spec` VARCHAR(50) DEFAULT NULL COMMENT '商品规格',
  `batch_no` VARCHAR(32) NOT NULL COMMENT '批次号',
  `production_date` DATETIME DEFAULT NULL COMMENT '生产日期',
  `expiry_date` DATETIME DEFAULT NULL COMMENT '有效期至',
  `type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '入库类型：1-采购 2-退货 3-调拨 4-补货',
  `quantity` INT UNSIGNED NOT NULL COMMENT '入库数量',
  `unit_cost` DECIMAL(10,2) DEFAULT NULL COMMENT '单位成本',
  `total_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '总成本',
  `warehouse_location` VARCHAR(50) NOT NULL COMMENT '仓储位置',
  `warehouse_zone` VARCHAR(50) DEFAULT NULL COMMENT '库区',
  `shelf_no` VARCHAR(50) DEFAULT NULL COMMENT '货架号',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态：0-待确认 1-已确认 2-已完成 3-已拒绝 4-已取消',
  `validation_result` JSON DEFAULT NULL COMMENT '前置校验结果',
  `is_synced` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已同步库存台账',
  `operator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '操作人员ID',
  `operator_name` VARCHAR(50) DEFAULT NULL COMMENT '操作人员名称',
  `confirmed_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '确认人ID',
  `confirmed_by_name` VARCHAR(50) DEFAULT NULL COMMENT '确认人名称',
  `confirmed_at` DATETIME DEFAULT NULL COMMENT '确认时间',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_inbound_no` (`inbound_no`),
  KEY `idx_goods_id` (`goods_id`),
  KEY `idx_batch_no` (`batch_no`),
  KEY `idx_warehouse_location` (`warehouse_location`),
  KEY `idx_status` (`status`),
  KEY `idx_type` (`type`),
  KEY `idx_operator_id` (`operator_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='仓储入库记录表';

DROP TABLE IF EXISTS `warehouse_outbound_records`;
CREATE TABLE `warehouse_outbound_records` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `outbound_no` VARCHAR(32) NOT NULL COMMENT '出库单号',
  `goods_id` BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  `goods_code` VARCHAR(100) NOT NULL COMMENT '商品编码',
  `goods_name` VARCHAR(255) NOT NULL COMMENT '商品名称',
  `goods_spec` VARCHAR(50) DEFAULT NULL COMMENT '商品规格',
  `batch_no` VARCHAR(32) NOT NULL COMMENT '批次号',
  `type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '出库类型：1-订单 2-调拨 3-样品 4-损耗',
  `quantity` INT UNSIGNED NOT NULL COMMENT '出库数量',
  `warehouse_location` VARCHAR(50) NOT NULL COMMENT '仓储位置',
  `order_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联订单ID',
  `order_no` VARCHAR(32) DEFAULT NULL COMMENT '关联订单号',
  `transfer_target_location` BIGINT UNSIGNED DEFAULT NULL COMMENT '调拨目标仓位置',
  `transfer_target_name` VARCHAR(50) DEFAULT NULL COMMENT '调拨目标仓',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态：0-待确认 1-已确认 2-已完成 3-已拒绝 4-已取消',
  `validation_result` JSON DEFAULT NULL COMMENT '前置校验结果',
  `is_over_quantity_intercepted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否超量出库拦截',
  `intercept_reason` VARCHAR(200) DEFAULT NULL COMMENT '拦截原因',
  `is_synced` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已同步库存台账',
  `operator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '操作人员ID',
  `operator_name` VARCHAR(50) DEFAULT NULL COMMENT '操作人员名称',
  `confirmed_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '确认人ID',
  `confirmed_by_name` VARCHAR(50) DEFAULT NULL COMMENT '确认人名称',
  `confirmed_at` DATETIME DEFAULT NULL COMMENT '确认时间',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_outbound_no` (`outbound_no`),
  KEY `idx_goods_id` (`goods_id`),
  KEY `idx_batch_no` (`batch_no`),
  KEY `idx_warehouse_location` (`warehouse_location`),
  KEY `idx_status` (`status`),
  KEY `idx_type` (`type`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_operator_id` (`operator_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='仓储出库记录表';

DROP TABLE IF EXISTS `warehouse_inventory_records`;
CREATE TABLE `warehouse_inventory_records` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `inventory_no` VARCHAR(32) NOT NULL COMMENT '库存编号',
  `goods_id` BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  `goods_code` VARCHAR(100) NOT NULL COMMENT '商品编码',
  `goods_name` VARCHAR(255) NOT NULL COMMENT '商品名称',
  `goods_spec` VARCHAR(50) DEFAULT NULL COMMENT '商品规格',
  `batch_no` VARCHAR(32) NOT NULL COMMENT '批次号',
  `production_date` DATETIME DEFAULT NULL COMMENT '生产日期',
  `expiry_date` DATETIME DEFAULT NULL COMMENT '有效期至',
  `warehouse_location` VARCHAR(50) NOT NULL COMMENT '仓储位置',
  `warehouse_zone` VARCHAR(50) DEFAULT NULL COMMENT '库区',
  `shelf_no` VARCHAR(50) DEFAULT NULL COMMENT '货架号',
  `system_quantity` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '系统库存数量',
  `actual_quantity` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '实际盘点数量',
  `diff_quantity` INT DEFAULT 0 COMMENT '差异数量',
  `inventory_type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '库存类型：1-正常 2-损耗 3-异常',
  `count_status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '盘点状态：0-待盘点 1-盘点中 2-已完成 3-已确认 4-已取消',
  `is_synced_front` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已同步前台库存',
  `is_synced_merchant` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已同步商家台账',
  `is_synced_logistics` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已同步物流备货',
  `normal_quantity` INT UNSIGNED DEFAULT 0 COMMENT '正常库存数量',
  `loss_quantity` INT UNSIGNED DEFAULT 0 COMMENT '损耗库存数量',
  `abnormal_quantity` INT UNSIGNED DEFAULT 0 COMMENT '异常库存数量',
  `loss_reason` VARCHAR(200) DEFAULT NULL COMMENT '损耗原因',
  `abnormal_reason` VARCHAR(200) DEFAULT NULL COMMENT '异常原因',
  `low_stock_threshold` INT UNSIGNED DEFAULT 0 COMMENT '低库存预警阈值',
  `is_low_stock_alert` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否触发低库存预警',
  `unit_price` DECIMAL(10,2) DEFAULT NULL COMMENT '库存单价',
  `total_amount` DECIMAL(14,2) DEFAULT NULL COMMENT '库存金额',
  `last_count_operator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '最后盘点人ID',
  `last_count_operator_name` VARCHAR(50) DEFAULT NULL COMMENT '最后盘点人名称',
  `last_count_time` DATETIME DEFAULT NULL COMMENT '最后盘点时间',
  `last_correct_operator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '最后修正人ID',
  `last_correct_operator_name` VARCHAR(50) DEFAULT NULL COMMENT '最后修正人名称',
  `last_correct_time` DATETIME DEFAULT NULL COMMENT '最后修正时间',
  `operator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '操作人员ID',
  `operator_name` VARCHAR(50) DEFAULT NULL COMMENT '操作人员名称',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_inventory_no` (`inventory_no`),
  KEY `idx_goods_id` (`goods_id`),
  KEY `idx_batch_no` (`batch_no`),
  KEY `idx_warehouse_location` (`warehouse_location`),
  KEY `idx_inventory_type` (`inventory_type`),
  KEY `idx_count_status` (`count_status`),
  KEY `idx_operator_id` (`operator_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='仓储库存记录表';

DROP TABLE IF EXISTS `warehouse_transfer_records`;
CREATE TABLE `warehouse_transfer_records` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `transfer_no` VARCHAR(32) NOT NULL COMMENT '调拨单号',
  `goods_id` BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  `goods_code` VARCHAR(100) NOT NULL COMMENT '商品编码',
  `goods_name` VARCHAR(255) NOT NULL COMMENT '商品名称',
  `goods_spec` VARCHAR(50) DEFAULT NULL COMMENT '商品规格',
  `batch_no` VARCHAR(32) NOT NULL COMMENT '批次号',
  `quantity` INT UNSIGNED NOT NULL COMMENT '调拨数量',
  `from_location` VARCHAR(50) NOT NULL COMMENT '调出仓储位置',
  `from_zone` VARCHAR(50) DEFAULT NULL COMMENT '调出库区',
  `to_location` VARCHAR(50) NOT NULL COMMENT '调入仓储位置',
  `to_zone` VARCHAR(50) DEFAULT NULL COMMENT '调入库区',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态：0-待审核 1-调拨中 2-已完成 3-已拒绝 4-已取消',
  `reason` VARCHAR(200) DEFAULT NULL COMMENT '调拨原因',
  `is_from_deducted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '调出仓是否已扣减',
  `is_to_added` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '调入仓是否已增加',
  `expected_arrival_time` DATETIME DEFAULT NULL COMMENT '预计到达时间',
  `actual_arrival_time` DATETIME DEFAULT NULL COMMENT '实际到达时间',
  `operator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '操作人员ID',
  `operator_name` VARCHAR(50) DEFAULT NULL COMMENT '操作人员名称',
  `reviewed_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '审核人ID',
  `reviewed_by_name` VARCHAR(50) DEFAULT NULL COMMENT '审核人名称',
  `reviewed_at` DATETIME DEFAULT NULL COMMENT '审核时间',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_transfer_no` (`transfer_no`),
  KEY `idx_goods_id` (`goods_id`),
  KEY `idx_batch_no` (`batch_no`),
  KEY `idx_from_location` (`from_location`),
  KEY `idx_to_location` (`to_location`),
  KEY `idx_status` (`status`),
  KEY `idx_operator_id` (`operator_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='仓储调拨记录表';

INSERT INTO `warehouse_inventory_records`
(`inventory_no`, `goods_id`, `goods_code`, `goods_name`, `goods_spec`, `batch_no`, `warehouse_location`, `warehouse_zone`, `shelf_no`, `system_quantity`, `actual_quantity`, `inventory_type`, `count_status`, `normal_quantity`, `loss_quantity`, `abnormal_quantity`, `low_stock_threshold`, `is_low_stock_alert`, `unit_price`, `total_amount`, `operator_id`, `operator_name`, `remark`)
VALUES
('WH20240601001', 1, 'SKU001', '智能手机Pro', '128GB 黑色', 'B2024060101', 'A仓-1区', 'A区', 'A-01-03', 500, 500, 1, 0, 500, 0, 0, 50, 0, 2999.00, 1499500.00, 1, '系统管理员', NULL),
('WH20240601002', 1, 'SKU001', '智能手机Pro', '256GB 白色', 'B2024060102', 'A仓-1区', 'A区', 'A-01-04', 300, 295, 1, 2, 295, 5, 0, 50, 0, 3299.00, 973050.00, 1, '系统管理员', '盘点差异5台'),
('WH20240601003', 2, 'SKU002', '无线蓝牙耳机', '标准版', 'B2024060103', 'B仓-2区', 'B区', 'B-02-01', 1000, 1000, 1, 0, 1000, 0, 0, 100, 0, 299.00, 299000.00, 1, '系统管理员', NULL),
('WH20240601004', 3, 'SKU003', '智能手表', '运动版 42mm', 'B2024060104', 'A仓-2区', 'A区', 'A-02-01', 30, 30, 1, 0, 30, 0, 0, 50, 1, 1599.00, 47970.00, 1, '系统管理员', '低库存预警'),
('WH20240601005', 4, 'SKU004', '平板电脑', '64GB WiFi版', 'B2024060105', 'C仓-1区', 'C区', 'C-01-01', 200, 180, 2, 3, 180, 20, 0, 30, 0, 2499.00, 449820.00, 1, '系统管理员', '确认损耗20台'),
('WH20240601006', 5, 'SKU005', '智能音箱', '旗舰版', 'B2024060106', 'B仓-1区', 'B区', 'B-01-05', 150, 120, 3, 0, 100, 10, 40, 30, 1, 499.00, 59880.00, 1, '系统管理员', '异常库存待排查');

SET FOREIGN_KEY_CHECKS = 1;
