const express = require('express')
const router = express.Router()
const accountPermissionController = require('../controllers/accountPermissionController')
const { authMiddleware, roleMiddleware } = require('../middlewares/auth')

router.get('/accounts', authMiddleware(), roleMiddleware(['super_admin', 'admin']), accountPermissionController.getAccountList)
router.get('/accounts/:id', authMiddleware(), roleMiddleware(['super_admin', 'admin']), accountPermissionController.getAccountDetail)
router.post('/assign-role', authMiddleware(), roleMiddleware(['super_admin']), accountPermissionController.assignRole)
router.post('/revoke-role', authMiddleware(), roleMiddleware(['super_admin']), accountPermissionController.revokeRole)
router.post('/add-permissions', authMiddleware(), roleMiddleware(['super_admin']), accountPermissionController.addPermissions)
router.post('/remove-permissions', authMiddleware(), roleMiddleware(['super_admin']), accountPermissionController.removePermissions)
router.put('/adjust/:id', authMiddleware(), roleMiddleware(['super_admin']), accountPermissionController.adjustPermissions)
router.post('/batch/assign-role', authMiddleware(), roleMiddleware(['super_admin']), accountPermissionController.batchAssignRole)
router.post('/batch/add-permissions', authMiddleware(), roleMiddleware(['super_admin']), accountPermissionController.batchAddPermissions)
router.get('/validate/status/:id', authMiddleware(), roleMiddleware(['super_admin', 'admin']), accountPermissionController.validateAccountStatus)
router.post('/validate/conflict', authMiddleware(), roleMiddleware(['super_admin', 'admin']), accountPermissionController.checkConflict)
router.get('/validate/role-match', authMiddleware(), roleMiddleware(['super_admin', 'admin']), accountPermissionController.checkRoleMatch)
router.get('/trace/:id', authMiddleware(), roleMiddleware(['super_admin', 'admin']), accountPermissionController.traceAccount)
router.post('/cleanup/:id', authMiddleware(), roleMiddleware(['super_admin']), accountPermissionController.cleanupRedundant)
router.get('/logs', authMiddleware(), roleMiddleware(['super_admin', 'admin']), accountPermissionController.getAccountLogs)

module.exports = router
