const express = require('express')
const router = express.Router()
const driverController = require('../controllers/driverController')

router.get('/', driverController.getList)
router.get('/audit/pending-count', driverController.getPendingAuditCount)
router.get('/audit/dashboard', driverController.getAuditDashboard)
router.get('/audit/check-expired', driverController.checkExpiredQualifications)
router.get('/:id', driverController.getDetail)
router.get('/:id/audit/logs', driverController.getAuditLogs)
router.get('/:id/audit/strictness', driverController.getAuditStrictness)
router.post('/', driverController.create)
router.post('/audit/batch', driverController.batchAudit)
router.post('/audit/batch-review', driverController.batchReview)
router.post('/audit/batch-remind', driverController.batchRemind)
router.post('/audit/batch-urgent', driverController.batchUrgent)
router.put('/:id', driverController.update)
router.put('/:id/status', driverController.updateStatus)
router.put('/:id/audit', driverController.audit)
router.put('/:id/audit/check-qualification', driverController.checkQualification)
router.put('/:id/upload-progress', driverController.updateUploadProgress)
router.delete('/:id', driverController.delete)

module.exports = router
