const express = require('express')
const router = express.Router()
const driverController = require('../controllers/driverController')

router.get('/', driverController.getList)
router.get('/audit/pending-count', driverController.getPendingAuditCount)
router.get('/audit/dashboard', driverController.getAuditDashboard)
router.get('/audit/check-expired', driverController.checkExpiredQualifications)
router.get('/status/dashboard', driverController.getStatusDashboard)
router.get('/:id', driverController.getDetail)
router.get('/:id/audit/logs', driverController.getAuditLogs)
router.get('/:id/audit/strictness', driverController.getAuditStrictness)
router.get('/:id/status/logs', driverController.getStatusLogs)
router.get('/:id/risk-level', driverController.getRiskLevel)
router.post('/', driverController.create)
router.post('/audit/batch', driverController.batchAudit)
router.post('/audit/batch-review', driverController.batchReview)
router.post('/audit/batch-remind', driverController.batchRemind)
router.post('/audit/batch-urgent', driverController.batchUrgent)
router.post('/status/batch-change', driverController.batchChangeAccountStatus)
router.post('/status/batch-temp-ban', driverController.batchTempBan)
router.post('/status/batch-remind', driverController.batchRemindRectification)
router.post('/status/batch-restore', driverController.batchRestoreNormal)
router.post('/status/pre-check-batch', driverController.preCheckBatchOperation)
router.put('/:id', driverController.update)
router.put('/:id/status', driverController.updateStatus)
router.put('/:id/account-status', driverController.changeAccountStatus)
router.put('/:id/audit', driverController.audit)
router.put('/:id/audit/check-qualification', driverController.checkQualification)
router.put('/:id/upload-progress', driverController.updateUploadProgress)
router.put('/:id/pre-check-status', driverController.preCheckStatusChange)
router.put('/:id/auto-judge-risk', driverController.autoJudgeRiskLevel)
router.delete('/:id', driverController.delete)

module.exports = router
