const express = require('express')
const router = express.Router()
const filterController = require('../controllers/filterController')
const { authMiddleware, roleMiddleware } = require('../middlewares/auth')

router.get('/', authMiddleware(), filterController.getList)
router.get('/trace', authMiddleware(), filterController.traceFilter)
router.get('/status/overview', authMiddleware(), filterController.getStatusOverview)
router.get('/category/trace', authMiddleware(), filterController.traceCategoryAdapt)
router.get('/category/adapts', authMiddleware(), filterController.getCategoryAdaptList)
router.get('/weight/logs', authMiddleware(), filterController.getWeightLogList)
router.get('/weight/trace', authMiddleware(), filterController.traceWeightHistory)
router.post('/validate', authMiddleware(), filterController.validateCreate)
router.post('/category/validate', authMiddleware(), filterController.validateCategoryBind)
router.post('/weight/validate', authMiddleware(), filterController.validateWeightAdjust)
router.post('/weight/adjust', authMiddleware(), roleMiddleware('super_admin', 'admin', 'operator'), filterController.adjustWeightStep)
router.post('/weight/batch-config', authMiddleware(), roleMiddleware('super_admin', 'admin', 'operator'), filterController.batchWeightConfig)
router.post('/entry', authMiddleware(), roleMiddleware('super_admin', 'admin', 'operator'), filterController.createWithValidation)
router.post('/batch-entry', authMiddleware(), roleMiddleware('super_admin', 'admin', 'operator'), filterController.batchValidateAndSubmit)
router.post('/batch-status', authMiddleware(), roleMiddleware('super_admin', 'admin', 'operator'), filterController.batchUpdateStatus)
router.post('/category/adjust', authMiddleware(), roleMiddleware('super_admin', 'admin', 'operator'), filterController.adjustCategoryStep)
router.post('/category/batch-migrate', authMiddleware(), roleMiddleware('super_admin', 'admin', 'operator'), filterController.batchCategoryMigrate)
router.get('/:id/edit-logs', authMiddleware(), filterController.getEditLogs)
router.get('/:id', authMiddleware(), filterController.getDetail)
router.put('/:id/constrain', authMiddleware(), filterController.updateWithConstraint)
router.put('/:id/status', authMiddleware(), filterController.updateStatus)
router.delete('/:id', authMiddleware(), filterController.delete)

module.exports = router
