const express = require('express')
const router = express.Router()

const authRoutes = require('./auth')
const resourceRoutes = require('./resources')
const templateRoutes = require('./templates')
const auditRoutes = require('./audit')
const userRoutes = require('./users')
const memberRoutes = require('./members')
const categoryRoutes = require('./categories')
const dashboardRoutes = require('./dashboard')
const violationRoutes = require('./violations')
const appealRoutes = require('./appeals')
const notificationRoutes = require('./notifications')
const logRoutes = require('./logs')
const systemLogRoutes = require('./systemLogs')
const cronLogRoutes = require('./cronLogs')
const serverMonitorRoutes = require('./serverMonitors')
const recycleRoutes = require('./recycles')
const rolePermissionRoutes = require('./rolePermissions')
const accountPermissionRoutes = require('./accountPermissions')
const filterRoutes = require('./filters')
const featuredWorkRoutes = require('./featuredWorks')
const resourceVisibilityRoutes = require('./resourceVisibility')

router.use('/auth', authRoutes)
router.use('/resources', resourceRoutes)
router.use('/templates', templateRoutes)
router.use('/audit', auditRoutes)
router.use('/users', userRoutes)
router.use('/members', memberRoutes)
router.use('/categories', categoryRoutes)
router.use('/dashboard', dashboardRoutes)
router.use('/violations', violationRoutes)
router.use('/appeals', appealRoutes)
router.use('/notifications', notificationRoutes)
router.use('/logs', logRoutes)
router.use('/system-logs', systemLogRoutes)
router.use('/cron-logs', cronLogRoutes)
router.use('/server-monitors', serverMonitorRoutes)
router.use('/recycles', recycleRoutes)
router.use('/role-permissions', rolePermissionRoutes)
router.use('/account-permissions', accountPermissionRoutes)
router.use('/filters', filterRoutes)
router.use('/featured-works', featuredWorkRoutes)
router.use('/resource-visibility', resourceVisibilityRoutes)

module.exports = router
