import { Router } from 'express';
import authRouter from './auth';
import goodsRouter from './goods';
import orderRouter from './order';
import userRouter from './user';
import userBatchRouter from './userBatch';
import userTraceRouter from './userTrace';
import marketingRouter from './marketing';
import afterSaleRouter from './aftersale';
import merchantRouter from './merchant';
import orderFlowRouter from './orderFlow';
import goodsAuditRouter from './goodsAudit';
import goodsAuditValidateRouter from './goodsAuditValidate';
import goodsAuditReviewRouter from './goodsAuditReview';
import goodsAuditBatchRouter from './goodsAuditBatch';
import goodsAuditTraceRouter from './goodsAuditTrace';
import merchantAuditRouter from './merchantAudit';
import marketingCalcRouter from './marketingCalc';
import afterSaleAuditRouter from './afterSaleAudit';
import penaltyRouter from './penalty';
import riskRouter from './risk';
import messageRouter from './message';
import operateLogRouter from './operateLog';
import statisticsRouter from './statistics';
import goodsValidateRouter from './goodsValidate';
import goodsEditorRouter from './goodsEditor';
import goodsBatchRouter from './goodsBatch';
import goodsTraceRouter from './goodsTrace';
import categoryRouter from './category';
import categoryValidateRouter from './categoryValidate';
import categoryLinkageRouter from './categoryLinkage';
import categoryBatchRouter from './categoryBatch';
import categoryTraceRouter from './categoryTrace';
import articleRouter from './article';
import articleValidateRouter from './articleValidate';
import articleEditorRouter from './articleEditor';
import articleBatchRouter from './articleBatch';
import articleTraceRouter from './articleTrace';
import orderValidateRouter from './orderValidate';
import orderBatchRouter from './orderBatch';
import orderTraceRouter from './orderTrace';
import paymentValidateRouter from './paymentValidate';
import paymentBatchRouter from './paymentBatch';
import paymentTraceRouter from './paymentTrace';
import shippingValidateRouter from './shippingValidate';
import logisticsBatchRouter from './logisticsBatch';
import logisticsTraceRouter from './logisticsTrace';
import afterSaleValidateRouter from './afterSaleValidate';
import afterSaleBatchRouter from './afterSaleBatch';
import afterSaleTraceRouter from './afterSaleTrace';
import merchantQualificationRouter from './merchantQualification';
import merchantQualificationAuditRouter from './merchantQualificationAudit';
import merchantQualificationBatchRouter from './merchantQualificationBatch';
import merchantQualificationTraceRouter from './merchantQualificationTrace';
import shopInfoRouter from './shopInfo';
import shopStatusRouter from './shopStatus';
import shopBatchRouter from './shopBatch';
import shopTraceRouter from './shopTrace';
import merchantBusinessRouter from './merchantBusiness';
import merchantBusinessCorrectRouter from './merchantBusinessCorrect';
import merchantBusinessBatchRouter from './merchantBusinessBatch';
import merchantBusinessTraceRouter from './merchantBusinessTrace';
import settleValidateRouter from './settleValidate';
import settleCalcRouter from './settleCalc';
import settleBatchRouter from './settleBatch';
import settleTraceRouter from './settleTrace';
import marketingValidateRouter from './marketingValidate';
import marketingBatchRouter from './marketingBatch';
import marketingTraceRouter from './marketingTrace';
import marketingProductAdmissionRouter from './marketingProductAdmission';
import marketingProductBatchRouter from './marketingProductBatch';
import marketingProductTraceRouter from './marketingProductTrace';

const router = Router();

router.use('/auth', authRouter);
router.use('/goods', goodsRouter);
router.use('/order', orderRouter);
router.use('/user', userRouter);
router.use('/userBatch', userBatchRouter);
router.use('/userTrace', userTraceRouter);
router.use('/marketing', marketingRouter);
router.use('/aftersale', afterSaleRouter);
router.use('/merchant', merchantRouter);
router.use('/orderFlow', orderFlowRouter);
router.use('/goodsAudit', goodsAuditRouter);
router.use('/goodsAuditValidate', goodsAuditValidateRouter);
router.use('/goodsAuditReview', goodsAuditReviewRouter);
router.use('/goodsAuditBatch', goodsAuditBatchRouter);
router.use('/goodsAuditTrace', goodsAuditTraceRouter);
router.use('/merchantAudit', merchantAuditRouter);
router.use('/marketingCalc', marketingCalcRouter);
router.use('/afterSaleAudit', afterSaleAuditRouter);
router.use('/penalty', penaltyRouter);
router.use('/risk', riskRouter);
router.use('/message', messageRouter);
router.use('/operateLog', operateLogRouter);
router.use('/statistics', statisticsRouter);
router.use('/goodsValidate', goodsValidateRouter);
router.use('/goodsEditor', goodsEditorRouter);
router.use('/goodsBatch', goodsBatchRouter);
router.use('/goodsTrace', goodsTraceRouter);
router.use('/category', categoryRouter);
router.use('/categoryValidate', categoryValidateRouter);
router.use('/categoryLinkage', categoryLinkageRouter);
router.use('/categoryBatch', categoryBatchRouter);
router.use('/categoryTrace', categoryTraceRouter);
router.use('/article', articleRouter);
router.use('/articleValidate', articleValidateRouter);
router.use('/articleEditor', articleEditorRouter);
router.use('/articleBatch', articleBatchRouter);
router.use('/articleTrace', articleTraceRouter);
router.use('/orderValidate', orderValidateRouter);
router.use('/orderBatch', orderBatchRouter);
router.use('/orderTrace', orderTraceRouter);
router.use('/paymentValidate', paymentValidateRouter);
router.use('/paymentBatch', paymentBatchRouter);
router.use('/paymentTrace', paymentTraceRouter);
router.use('/shippingValidate', shippingValidateRouter);
router.use('/logisticsBatch', logisticsBatchRouter);
router.use('/logisticsTrace', logisticsTraceRouter);
router.use('/afterSaleValidate', afterSaleValidateRouter);
router.use('/afterSaleBatch', afterSaleBatchRouter);
router.use('/afterSaleTrace', afterSaleTraceRouter);
router.use('/merchantQualification', merchantQualificationRouter);
router.use('/merchantQualificationAudit', merchantQualificationAuditRouter);
router.use('/merchantQualificationBatch', merchantQualificationBatchRouter);
router.use('/merchantQualificationTrace', merchantQualificationTraceRouter);
router.use('/shopInfo', shopInfoRouter);
router.use('/shopStatus', shopStatusRouter);
router.use('/shopBatch', shopBatchRouter);
router.use('/shopTrace', shopTraceRouter);
router.use('/merchantBusiness', merchantBusinessRouter);
router.use('/merchantBusinessCorrect', merchantBusinessCorrectRouter);
router.use('/merchantBusinessBatch', merchantBusinessBatchRouter);
router.use('/merchantBusinessTrace', merchantBusinessTraceRouter);
router.use('/settleValidate', settleValidateRouter);
router.use('/settleCalc', settleCalcRouter);
router.use('/settleBatch', settleBatchRouter);
router.use('/settleTrace', settleTraceRouter);
router.use('/marketing', marketingValidateRouter);
router.use('/marketing', marketingBatchRouter);
router.use('/marketing', marketingTraceRouter);
router.use('/marketing/product', marketingProductAdmissionRouter);
router.use('/marketing/product', marketingProductBatchRouter);
router.use('/marketing/product', marketingProductTraceRouter);

export default router;
