const express = require('express')
const router = express.Router()
const marketingController = require('../controllers/marketingController')

router.get('/scene-config', marketingController.getSceneConfig)
router.get('/risk-stats', marketingController.getRiskStats)
router.post('/validate', marketingController.validateCampaignConfig)
router.post('/validate/:id', marketingController.validateCampaignConfig)
router.post('/batch/copy', marketingController.batchCopy)
router.post('/batch/update', marketingController.batchUpdate)
router.post('/batch/status', marketingController.batchUpdateStatus)
router.post('/batch/city-tier', marketingController.batchUpdateCityTier)
router.get('/statistics/:id', marketingController.getStatistics)
router.get('/audit/:id', marketingController.getAuditList)
router.post('/copy/:id', marketingController.copyCampaign)
router.put('/:id/status', marketingController.updateStatus)

router.get('/audience/config', marketingController.getAudienceConfig)
router.post('/audience/strategy/:purpose', marketingController.applyAudienceStrategy)
router.post('/audience/preview', marketingController.previewAudience)
router.post('/audience/verify', marketingController.verifyUserEligibility)
router.post('/audience/:id/import', marketingController.batchImportAudience)
router.post('/audience/:id/exclude', marketingController.batchExcludeAudience)
router.post('/audience/:id/tags', marketingController.batchUpdateUserTags)
router.put('/audience/:id/weights', marketingController.updateAudienceWeights)
router.get('/audience/:id/logs', marketingController.getCampaignAudienceLogs)
router.get('/audience-risk-stats', marketingController.getAudienceRiskStats)

router.get('/:id', marketingController.getDetail)
router.put('/:id', marketingController.update)
router.delete('/:id', marketingController.delete)
router.get('/', marketingController.getList)
router.post('/', marketingController.create)

module.exports = router
