const express = require('express')
const router = express.Router()
const marketingController = require('../controllers/marketingController')

router.get('/scene-config', marketingController.getSceneConfig)
router.get('/risk-stats', marketingController.getRiskStats)
router.post('/validate', marketingController.validateCampaignConfig)
router.post('/validate/:id', marketingController.validateCampaignConfig)
router.post('/batch/copy', marketingController.batchCopy)
router.post('/batch/update', marketingController.batchUpdate)
router.post('/batch/status', marketingController.batchUpdateStatus)
router.post('/batch/city-tier', marketingController.batchUpdateCityTier)
router.get('/statistics/:id', marketingController.getStatistics)
router.get('/effect/:id', marketingController.getStatisticsDetail)
router.post('/effect/evaluate/:id', marketingController.evaluateCampaignEffect)
router.post('/effect/batch-evaluate', marketingController.batchEvaluate)
router.get('/effect/funnel/:id', marketingController.getEffectFunnel)
router.get('/effect/fraud/:id', marketingController.getFraudInterceptList)
router.get('/effect/export-config', marketingController.getExportConfig)
router.post('/effect/batch-export', marketingController.batchExportReports)
router.post('/effect/batch-compare', marketingController.batchCompareCampaigns)
router.post('/effect/batch-mark-inefficient', marketingController.batchMarkInefficient)
router.put('/effect/:id/template', marketingController.toggleTemplate)
router.get('/audit/:id', marketingController.getAuditList)
router.post('/copy/:id', marketingController.copyCampaign)
router.put('/:id/status', marketingController.updateStatus)

router.get('/audience/config', marketingController.getAudienceConfig)
router.post('/audience/strategy/:purpose', marketingController.applyAudienceStrategy)
router.post('/audience/preview', marketingController.previewAudience)
router.post('/audience/verify', marketingController.verifyUserEligibility)
router.post('/audience/:id/import', marketingController.batchImportAudience)
router.post('/audience/:id/exclude', marketingController.batchExcludeAudience)
router.post('/audience/:id/tags', marketingController.batchUpdateUserTags)
router.put('/audience/:id/weights', marketingController.updateAudienceWeights)
router.get('/audience/:id/logs', marketingController.getCampaignAudienceLogs)
router.get('/audience-risk-stats', marketingController.getAudienceRiskStats)

router.get('/redemption/config', marketingController.getRedemptionConfig)
router.post('/redemption/pre-check/:id', marketingController.preCheckRedemptionCtrl)
router.post('/redemption/submit/:id', marketingController.submitRedemptionCtrl)
router.post('/redemption/review/:id', marketingController.manualReviewRedemption)
router.post('/redemption/batch-review', marketingController.batchManualReviewRedemption)
router.get('/redemption/list/:id', marketingController.getRedemptionListCtrl)
router.get('/redemption/stats/:id', marketingController.getRedemptionStatsCtrl)
router.put('/redemption/revoke/:id', marketingController.revokeRedemptionCtrl)
router.get('/redemption/trace/:id', marketingController.getRedemptionTrace)
router.get('/redemption/violations', marketingController.getViolationList)
router.post('/redemption/batch-reject', marketingController.batchRejectViolationCtrl)
router.post('/redemption/batch-pending/:id', marketingController.batchReviewPendingCtrl)
router.get('/redemption/compliance/:id', marketingController.getComplianceOverviewCtrl)

router.get('/:id', marketingController.getDetail)
router.put('/:id', marketingController.update)
router.delete('/:id', marketingController.delete)
router.get('/', marketingController.getList)
router.post('/', marketingController.create)

module.exports = router
