const express = require('express')
const router = express.Router()
const marketingController = require('../controllers/marketingController')

router.get('/scene-config', marketingController.getSceneConfig)
router.get('/risk-stats', marketingController.getRiskStats)
router.post('/validate', marketingController.validateCampaignConfig)
router.post('/validate/:id', marketingController.validateCampaignConfig)
router.post('/batch/copy', marketingController.batchCopy)
router.post('/batch/update', marketingController.batchUpdate)
router.post('/batch/status', marketingController.batchUpdateStatus)
router.post('/batch/city-tier', marketingController.batchUpdateCityTier)
router.get('/statistics/:id', marketingController.getStatistics)
router.get('/audit/:id', marketingController.getAuditList)
router.post('/copy/:id', marketingController.copyCampaign)
router.put('/:id/status', marketingController.updateStatus)
router.get('/:id', marketingController.getDetail)
router.put('/:id', marketingController.update)
router.delete('/:id', marketingController.delete)
router.get('/', marketingController.getList)
router.post('/', marketingController.create)

module.exports = router
