const express = require('express')
const router = express.Router()
const orderController = require('../controllers/orderController')
const { requireRole } = require('../middleware/auth')

router.get('/', orderController.getList)
router.get('/statistics', orderController.getStatistics)
router.get('/cancel-statistics', orderController.getCancelStatistics)
router.get('/abnormal', orderController.getAbnormalOrders)
router.get('/violations', orderController.getViolationLogs)
router.get('/trace/history', orderController.getTraceHistory)
router.get('/trace/:orderNo', orderController.getOrderTrace)
router.get('/flow/:id', orderController.getFlowDetail)
router.get('/:id', orderController.getDetail)
router.get('/:id/edit-conditions', orderController.getEditConditions)
router.get('/:id/status-logs', orderController.getStatusLogs)
router.get('/:id/actions', orderController.getAvailableActions)
router.get('/:id/prerequisites', orderController.getTransitionPrerequisites)
router.post('/', orderController.create)
router.post('/validate-price', orderController.validatePrice)
router.post('/batch-price-rule', requireRole([1, 2]), orderController.batchUpdatePriceRule)
router.post('/batch-abnormal', orderController.batchAbnormalOperation)
router.put('/:id', orderController.update)
router.put('/:id/base-info', orderController.updateBaseInfo)
router.delete('/:id', orderController.delete)
router.put('/:id/status', orderController.updateStatus)
router.put('/:id/dispatch', orderController.dispatch)
router.put('/:id/cancel', orderController.cancel)
router.put('/:id/complete', orderController.completeOrder)
router.post('/batch-dispatch', orderController.batchDispatch)

module.exports = router
