const express = require('express')
const router = express.Router()
const passengerController = require('../controllers/passengerController')

router.get('/', passengerController.getList)
router.get('/validate/phone', passengerController.validatePhone)
router.post('/validate/idcard', passengerController.validateIdCard)
router.post('/batch', passengerController.batchOperation)
router.post('/export', passengerController.createExportTask)
router.get('/export/list', passengerController.getExportTaskList)
router.get('/travel-permission', passengerController.checkTravelPermission)
router.get('/:id', passengerController.getDetail)
router.post('/', passengerController.create)
router.put('/:id', passengerController.update)
router.delete('/:id', passengerController.delete)
router.put('/:id/status', passengerController.updateStatus)
router.get('/:id/validate-update', passengerController.validateBeforeUpdate)
router.put('/:id/update-with-validation', passengerController.updateWithValidation)
router.post('/:id/calculate-level', passengerController.calculateLevel)
router.get('/:id/audit-logs', passengerController.getAuditLogs)
router.get('/:id/operation-logs', passengerController.getOperationLogs)
router.get('/:id/risk-overview', passengerController.getRiskOverview)
router.put('/:id/tags', passengerController.updateTags)
router.get('/:id/travel-records', passengerController.getTravelRecords)
router.post('/:id/calculate-travel-risk', passengerController.calculateTravelRisk)
router.get('/:id/travel-risks', passengerController.getTravelRiskList)
router.get('/:id/travel-trace/:orderId', passengerController.getTravelTraceDetail)
router.post('/:id/behavior-report', passengerController.createBehaviorReport)
router.get('/:id/behavior-reports', passengerController.getBehaviorReportList)
router.get('/:id/behavior-report/:reportId', passengerController.getBehaviorReportDetail)
router.put('/:id/behavior-report/:reportId/review', passengerController.reviewBehaviorReport)

module.exports = router
