const express = require('express')
const router = express.Router()
const passengerController = require('../controllers/passengerController')

router.get('/', passengerController.getList)
router.get('/validate/phone', passengerController.validatePhone)
router.post('/validate/idcard', passengerController.validateIdCard)
router.post('/batch', passengerController.batchOperation)
router.get('/:id', passengerController.getDetail)
router.post('/', passengerController.create)
router.put('/:id', passengerController.update)
router.delete('/:id', passengerController.delete)
router.put('/:id/status', passengerController.updateStatus)
router.get('/:id/validate-update', passengerController.validateBeforeUpdate)
router.put('/:id/update-with-validation', passengerController.updateWithValidation)
router.post('/:id/calculate-level', passengerController.calculateLevel)
router.get('/:id/audit-logs', passengerController.getAuditLogs)
router.get('/:id/operation-logs', passengerController.getOperationLogs)
router.get('/:id/risk-overview', passengerController.getRiskOverview)
router.put('/:id/tags', passengerController.updateTags)

module.exports = router
