const express = require('express')
const router = express.Router()
const resourceController = require('../controllers/resourceController')
const { authMiddleware, roleMiddleware } = require('../middlewares/auth')

router.get('/', authMiddleware(), resourceController.getList)
router.get('/hot/list', authMiddleware(), resourceController.getHotResources)
router.get('/trace', authMiddleware(), resourceController.traceMaterial)
router.post('/', authMiddleware(), resourceController.create)
router.post('/validate', authMiddleware(), resourceController.validateCreate)
router.post('/entry', authMiddleware(), roleMiddleware('super_admin', 'admin', 'operator'), resourceController.createWithValidation)
router.post('/batch-weight', authMiddleware(), resourceController.batchUpdateWeight)
router.post('/batch-toggle', authMiddleware(), resourceController.batchToggleStatus)
router.post('/batch-delete', authMiddleware(), resourceController.batchDelete)
router.post('/batch-status', authMiddleware(), resourceController.batchUpdateStatus)
router.get('/state/exclusive', authMiddleware(), resourceController.checkStateExclusive)
router.get('/permission-filter', authMiddleware(), resourceController.getPermissionFilter)
router.get('/state/history', authMiddleware(), resourceController.getStateChangeHistory)
router.get('/:id/related-works', authMiddleware(), resourceController.getRelatedWorks)
router.post('/batch-change-state', authMiddleware(), resourceController.batchChangeState)
router.put('/:id/state', authMiddleware(), resourceController.changeStateWithValidation)
router.get('/:id', authMiddleware(), resourceController.getDetail)
router.put('/:id', authMiddleware(), resourceController.update)
router.put('/:id/constrain', authMiddleware(), resourceController.updateWithConstraint)
router.delete('/:id', authMiddleware(), resourceController.delete)
router.put('/:id/status', authMiddleware(), resourceController.updateStatus)
router.post('/:id/submit-audit', authMiddleware(), resourceController.submitForAudit)
router.post('/:id/publish', authMiddleware(), resourceController.publishResource)
router.post('/:id/offline', authMiddleware(), resourceController.offlineResource)
router.post('/:id/block', authMiddleware(), roleMiddleware('super_admin', 'admin', 'auditor'), resourceController.blockResource)
router.post('/:id/unblock', authMiddleware(), roleMiddleware('super_admin', 'admin', 'auditor'), resourceController.unblockResource)

module.exports = router
