const express = require('express')
const router = express.Router()
const userController = require('../controllers/userController')
const { authMiddleware, roleMiddleware } = require('../middlewares/auth')

router.get('/', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getList)
router.get('/validate', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.validateAccount)
router.get('/trace', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.traceAccount)
router.get('/compliance-logs', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.getComplianceLogs)
router.get('/:id/risk-preview', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getRiskPreview)
router.get('/:id', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getDetail)
router.get('/:id/edit-logs', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.getEditLogs)
router.get('/:userId/status-logs', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getStatusLogs)
router.get('/:userId/change-stats', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getChangeStats)
router.post('/', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.create)
router.put('/:id', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.update)
router.delete('/:id', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.delete)
router.post('/batch-delete', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.batchDelete)
router.post('/batch-update', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.batchUpdate)
router.post('/batch-change-status', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.batchChangeStatus)
router.put('/:id/status', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.updateStatus)

module.exports = router
