const express = require('express')
const router = express.Router()
const userController = require('../controllers/userController')
const { authMiddleware, roleMiddleware } = require('../middlewares/auth')

router.get('/', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getList)
router.get('/validate', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.validateAccount)
router.get('/trace', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.traceAccount)
router.get('/compliance-logs', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.getComplianceLogs)
router.get('/:id/risk-preview', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getRiskPreview)
router.get('/:id', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getDetail)
router.get('/:id/edit-logs', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.getEditLogs)
router.get('/:userId/status-logs', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getStatusLogs)
router.get('/:userId/change-stats', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getChangeStats)
router.post('/', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.create)
router.put('/:id', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.update)
router.delete('/:id', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.delete)
router.post('/batch-delete', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.batchDelete)
router.post('/batch-update', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.batchUpdate)
router.post('/batch-change-status', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.batchChangeStatus)
router.put('/:id/status', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.updateStatus)

// 层级管理
router.get('/level/criteria-meta', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getLevelCriteriaMeta)
router.get('/:userId/level-preview', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getLevelPreview)
router.put('/:userId/level', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.changeLevel)
router.get('/:userId/level-logs', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getLevelLogs)

// 标签管理
router.get('/tag/meta', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getTagMeta)
router.get('/tag/validate-name', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.validateTagName)
router.get('/tag/definitions', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.listTagDefinitions)
router.post('/tag/definitions', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.createTagDefinition)
router.put('/tag/definitions/:id', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.updateTagDefinition)
router.get('/:userId/tag-match', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.checkUserTagMatch)
router.post('/:userId/tags', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.addUserTags)
router.delete('/:userId/tags', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.removeUserTags)
router.post('/tag/batch-apply', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor']), userController.batchApplyTags)
router.get('/:userId/tag-logs', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getTagLogs)
router.get('/:userId/tag-trace', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getTagTrace)
router.post('/:userId/tag-clean', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.cleanRedundantTags)

// 登录行为管控
router.get('/login/thresholds-meta', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getLoginThresholdsMeta)
router.get('/login/logs', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.queryLoginLogs)
router.get('/login/:loginId/detail', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getLoginDetail)
router.put('/login/:loginId/mark-risk', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor']), userController.markRiskLog)
router.put('/login/:loginId/clear-risk', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.clearRiskLog)
router.put('/login/:loginId/verify', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.verifyLoginRecord)
router.post('/login/batch-process', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor']), userController.batchProcessLoginLogs)
router.get('/:userId/login-devices', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.listLoginDevices)
router.put('/:userId/login-devices/:deviceId/lock', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.lockLoginDevice)
router.put('/:userId/login-devices/:deviceId/unlock', authMiddleware(), roleMiddleware(['super_admin', 'admin']), userController.unlockLoginDevice)
router.get('/:userId/login-risk-summary', authMiddleware(), roleMiddleware(['super_admin', 'admin', 'auditor', 'operator']), userController.getLoginRiskSummary)

module.exports = router
