const express = require('express')
const router = express.Router()
const vehicleController = require('../controllers/vehicleController')

router.get('/', vehicleController.getList)
router.get('/capacity/dashboard', vehicleController.getCapacityDashboard)
router.get('/check/plate', vehicleController.checkPlate)
router.get('/check/vin', vehicleController.checkVIN)
router.post('/validate', vehicleController.validateVehicleData)
router.post('/status/change', vehicleController.changeOperationStatus)
router.post('/batch/import', vehicleController.batchImport)
router.post('/batch/review', vehicleController.batchReview)
router.post('/batch/expired', vehicleController.batchMarkExpired)
router.post('/batch/lock', vehicleController.batchLock)
router.post('/batch/restore', vehicleController.batchRestoreOperation)
router.post('/batch/maintenance', vehicleController.batchInitiateMaintenance)
router.post('/batch/remind-renewal', vehicleController.batchRemindRenewal)
router.post('/batch/compliance-check', vehicleController.batchComplianceCheck)
router.post('/batch/remind-rectification', vehicleController.batchRemindRectification)
router.get('/compliance/standards', vehicleController.getComplianceStandardsByCity)
router.post('/compliance/validate-field', vehicleController.validateComplianceField)
router.post('/auto-check', vehicleController.autoCheckStatus)
router.get('/import/template', vehicleController.getImportTemplate)
router.post('/', vehicleController.create)
router.get('/:id', vehicleController.getDetail)
router.put('/:id', vehicleController.update)
router.delete('/:id', vehicleController.delete)
router.put('/:id/status', vehicleController.updateStatus)
router.put('/:id/audit', vehicleController.audit)
router.post('/:id/recalculate-level', vehicleController.recalculateLevel)
router.get('/:vehicleId/logs', vehicleController.getAuditLogs)
router.get('/:vehicleId/maintenance', vehicleController.getMaintenanceRecords)
router.post('/:vehicleId/maintenance', vehicleController.createMaintenanceRecord)
router.put('/:id/maintenance/:recordId', vehicleController.updateMaintenanceRecord)
router.get('/:vehicleId/violations', vehicleController.getViolationRecords)
router.post('/:vehicleId/violations', vehicleController.createViolationRecord)
router.get('/:vehicleId/status-logs', vehicleController.getStatusLogs)
router.get('/:vehicleId/compliance-checks', vehicleController.getComplianceChecks)
router.post('/:id/compliance-check', vehicleController.performCheck)
router.get('/:vehicleId/compliance-report', vehicleController.exportComplianceReport)
router.get('/:vehicleId/rectifications', vehicleController.getRectifications)
router.post('/:vehicleId/rectification', vehicleController.createRectification)
router.put('/:id/rectification/:rectId/review', vehicleController.reviewRectification)

module.exports = router
