const express = require('express')
const router = express.Router()
const vehicleController = require('../controllers/vehicleController')

router.get('/', vehicleController.getList)
router.get('/:id', vehicleController.getDetail)
router.get('/check/plate', vehicleController.checkPlate)
router.get('/check/vin', vehicleController.checkVIN)
router.post('/validate', vehicleController.validateVehicleData)
router.post('/', vehicleController.create)
router.put('/:id', vehicleController.update)
router.delete('/:id', vehicleController.delete)
router.put('/:id/status', vehicleController.updateStatus)
router.put('/:id/audit', vehicleController.audit)
router.get('/:vehicleId/logs', vehicleController.getAuditLogs)
router.post('/batch/import', vehicleController.batchImport)
router.post('/batch/review', vehicleController.batchReview)
router.post('/batch/expired', vehicleController.batchMarkExpired)
router.post('/batch/lock', vehicleController.batchLock)
router.get('/import/template', vehicleController.getImportTemplate)
router.post('/:id/recalculate-level', vehicleController.recalculateLevel)

module.exports = router
